extends: spectral:oas
rules:
  tag-description:
    description: Tags must have a description.
    given: $.tags[*]
    severity: warn
    then:
      field: description
      function: truthy

  no-delete-accounts:
    description: DELETE operations on accounts are not permitted
    severity: error
    given: "$.paths[*].delete"
    then:
      function: falsy
